###
GET http://localhost:8000/account/ HTTP/1.1

# Registration API
###
POST http://localhost:8000/account/register/ HTTP/1.1
Content-Type: application/json

{
    "email": "sakardahal1234@gmail.com",
    "name": "admin",
    "password": "admin",
    "confirm_password": "admin"
}

# Activate the account:
###
http://localhost:8000/account/activate/MTM/cq3dwr-0e78b229a2073f69c66df55f01008439/

# Access and Refresh Token Obtain:
###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "email": "sakar1234dahal@gmail.com",
    "password": "newpassword123"
}

# Login API
###
POST http://localhost:8000/account/login/ HTTP/1.1
Content-Type: application/json

{
    "email": "sakardahal1234@gmail.com",
    "password": "admin"
}

# Password Reset Link Send
###
POST http://localhost:8000/account/password-reset/ HTTP/1.1
Content-Type: application/json

{
    "email": "sakar1234dahal@gmail.com"
}


###
# Example of the frontend request from the mail. Attach the extra info in the request again while sending request for password-reset POST req
# https://your-frontend.com/reset-password/confirm/MTE/cq2awy-f1a44fad0f32770e1346d427fed1e1b4/

###
POST http://localhost:8000/account/password-reset-confirm/MTE/cq2awy-f1a44fad0f32770e1346d427fed1e1b4/ HTTP/1.1
Content-Type: application/json

{
    "new_password1": "newpassword123",
    "new_password2": "newpassword123"
}

# Entering a url entry
###
POST http://localhost:8000/url/shorten/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4MzI2ODcwLCJpYXQiOjE3NDgzMjQ0NzAsImp0aSI6IjRkZjBmODQyYWY4MjRmZTliZjRjZGRmYTc2YmEyZGNmIiwidXNlcl9pZCI6MTR9.6r305JDPhArZrrKgdsC2NOZugst6eZjwpnqajuuVVCU

{
    "original_url": "https://www.dj4e.com"
}

# Redirecting to the orginal page
###
GET http://localhost:8000/url/redirect/zdm0K8/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4MzI5ODk4LCJpYXQiOjE3NDgzMjc0OTgsImp0aSI6ImMwNjU4Y2UzMzIyNzQ3NzA5ZGRlYzI3NGIyYmM2NDUwIiwidXNlcl9pZCI6MTR9.PrxOjeEScvb_VX2yYytlWuluOgEbpz9pls5-Wic8YEo

###
GET http://localhost:8000/url/url_list/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4MzI5ODk4LCJpYXQiOjE3NDgzMjc0OTgsImp0aSI6ImMwNjU4Y2UzMzIyNzQ3NzA5ZGRlYzI3NGIyYmM2NDUwIiwidXNlcl9pZCI6MTR9.PrxOjeEScvb_VX2yYytlWuluOgEbpz9pls5-Wic8YEo

# Get one of the url instance
###
GET http://localhost:8000/url/12/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4MzI5ODk4LCJpYXQiOjE3NDgzMjc0OTgsImp0aSI6ImMwNjU4Y2UzMzIyNzQ3NzA5ZGRlYzI3NGIyYmM2NDUwIiwidXNlcl9pZCI6MTR9.PrxOjeEScvb_VX2yYytlWuluOgEbpz9pls5-Wic8YEo

###
PUT http://localhost:8000/url/3/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NzMzMjEyLCJpYXQiOjE3NDc3MzI5MTIsImp0aSI6ImMzOTJhZDU3MWFiMDQ0Yzk4YzQyYjliMmY2NWRiOTg3IiwidXNlcl9pZCI6MTN9.R4wHKxVTOpK8JU17_36XDL377YFv_xK1BslQrn8T1wE

{
    "original_url": "https://www.youtube.com"
}

###
DELETE  http://localhost:8000/url/3/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NzMzMjEyLCJpYXQiOjE3NDc3MzI5MTIsImp0aSI6ImMzOTJhZDU3MWFiMDQ0Yzk4YzQyYjliMmY2NWRiOTg3IiwidXNlcl9pZCI6MTN9.R4wHKxVTOpK8JU17_36XDL377YFv_xK1BslQrn8T1wE
