###
GET http://localhost:8000/account/ HTTP/1.1

# Registration API
###
POST http://localhost:8000/account/register/ HTTP/1.1
Content-Type: application/json

{
    "email": "sakardahal1234@gmail.com",
    "name": "admin",
    "password": "admin",
    "confirm_password": "admin"
}

# Activate the account:
###
http://localhost:8000/account/activate/MTM/cq3dwr-0e78b229a2073f69c66df55f01008439/

# Access and Refresh Token Obtain:
###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "email": "sakar1234dahal@gmail.com",
    "password": "newpassword123"
}

# Login API
###
POST http://localhost:8000/account/login/ HTTP/1.1
Content-Type: application/json

{
    "email": "sakardahal1234@gmail.com",
    "password": "admin"
}

# Password Reset Link Send
###
POST http://localhost:8000/account/password-reset/ HTTP/1.1
Content-Type: application/json

{
    "email": "sakar1234dahal@gmail.com"
}


###
# Example of the frontend request from the mail. Attach the extra info in the request again while sending request for password-reset POST req
# https://your-frontend.com/reset-password/confirm/MTE/cq2awy-f1a44fad0f32770e1346d427fed1e1b4/

###
POST http://localhost:8000/account/password-reset-confirm/MTE/cq2awy-f1a44fad0f32770e1346d427fed1e1b4/ HTTP/1.1
Content-Type: application/json

{
    "new_password1": "newpassword123",
    "new_password2": "newpassword123"
}

# Entering a url entry
###
POST http://localhost:8000/url/shorten/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NzMzMjEyLCJpYXQiOjE3NDc3MzI5MTIsImp0aSI6ImMzOTJhZDU3MWFiMDQ0Yzk4YzQyYjliMmY2NWRiOTg3IiwidXNlcl9pZCI6MTN9.R4wHKxVTOpK8JU17_36XDL377YFv_xK1BslQrn8T1wE

{
    "original_url": "https://www.youtube.com"
}

# Redirecting to the orginal page
###
GET http://localhost:8000/url/redirect/BS0HEA/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NzA4MDQ3LCJpYXQiOjE3NDc3MDc3NDcsImp0aSI6IjY1N2QwOGQzOTI4ZjQzYTdiZjJiNWZhYTE3ZjgyZWQ3IiwidXNlcl9pZCI6MTF9.-ERgVGVfINp2Tkyszxw0xtEfbHdMXk8yyMRrUPK6i3s

###
GET http://localhost:8000/url/url_list/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NzA5MDIwLCJpYXQiOjE3NDc3MDg3MjAsImp0aSI6IjEyOGJlN2IzNDBlZTQ2NDlhNWY4NzQ2NWYwYTE0NDllIiwidXNlcl9pZCI6MTN9.HrYc5bzKXuDCu1y2_gblV8FK2uMneNmYLwSrIYm_EUM

# Get one of the url instance
###
GET http://localhost:8000/url/2/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NzMzMTI3LCJpYXQiOjE3NDc3MzI4MjcsImp0aSI6ImEwNGUzMGEwMmU5MjRiMWViMjlkNWRhMWNjMjY5MTVkIiwidXNlcl9pZCI6MTF9.kyQcjBDl7dlt0qQL7KDKY7J_ETh5LNh-tcavZFLr7Jk

###
PUT http://localhost:8000/url/3/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NzMzMjEyLCJpYXQiOjE3NDc3MzI5MTIsImp0aSI6ImMzOTJhZDU3MWFiMDQ0Yzk4YzQyYjliMmY2NWRiOTg3IiwidXNlcl9pZCI6MTN9.R4wHKxVTOpK8JU17_36XDL377YFv_xK1BslQrn8T1wE

{
    "original_url": "https://www.youtube.com"
}

###
DELETE  http://localhost:8000/url/3/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NzMzMjEyLCJpYXQiOjE3NDc3MzI5MTIsImp0aSI6ImMzOTJhZDU3MWFiMDQ0Yzk4YzQyYjliMmY2NWRiOTg3IiwidXNlcl9pZCI6MTN9.R4wHKxVTOpK8JU17_36XDL377YFv_xK1BslQrn8T1wE
